apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-spgbv
  creationTimestamp: '2024-02-19T19:22:51Z'
  finalizers:
    - wrangler.cattle.io/cloud-config-secret-remover
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
  generation: 2
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
        f:spec:
          f:rkeConfig:
            f:machinePoolDefaults: {}
            f:upgradeStrategy:
              f:controlPlaneDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
              f:workerDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
      manager: rancher-v2.8.2-secret-migrator
      operation: Update
      time: '2024-02-19T19:22:51Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2024-02-19T19:22:52Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2024-02-19T19:23:05Z'
  name: nurullahkocaaslan
  namespace: fleet-default
  resourceVersion: '1650214'
  uid: f7724b17-574e-4365-8881-bdde4be422df
spec:
  kubernetesVersion: v1.27.10+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  clusterName: c-m-6bp7dl79
  conditions:
    - lastUpdateTime: '2024-02-19T19:22:51Z'
      reason: Reconciling
      status: 'True'
      type: Reconciling
    - lastUpdateTime: '2024-02-19T19:22:51Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-02-19T19:23:05Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2024-02-19T19:22:51Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2024-02-19T19:22:51Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2024-02-19T19:22:51Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2024-02-19T19:22:52Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      message: >-
        waiting for at least one control plane, etcd, and worker node to be
        registered
      reason: Waiting
      status: Unknown
      type: Updated
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      message: >-
        waiting for at least one control plane, etcd, and worker node to be
        registered
      reason: Waiting
      status: Unknown
      type: Provisioned
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      message: >-
        waiting for at least one control plane, etcd, and worker node to be
        registered
      reason: Waiting
      status: Unknown
      type: Ready
    - lastUpdateTime: '2024-02-19T19:22:53Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2024-02-19T19:22:54Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2024-02-19T19:23:05Z'
      status: 'False'
      type: Connected
  fleetWorkspaceName: fleet-default
  observedGeneration: 2
